---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  package: crossplane/provider-aws:v0.31.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
