---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  package: crossplane/provider-aws:v0.31.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-credentials
      key: credentials