---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gcp
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  package: crossplane/provider-gcp:v0.21.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
---
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  projectID: oam-proj
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-credentials
      key: credentials