apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.13.4
    helm:
      releaseName: cilium
      parameters:
        - name: kubeProxyReplacement
          value: strict
        - name: k8sServicePort
          value: "6443"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
