apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configurations
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: configurations
    repoURL: https://github.com/motilayo/argocd-apps.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
