apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: crossplane-helm
 namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.9.0
    helm:
      releaseName: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true