apiVersion: terraform.core.oam.dev/v1
kind: Provider
metadata:
  name: azure
  namespace: vela-system
  labels:
    config.oam.dev/catalog: velacore-config
    config.oam.dev/type: terraform-provider
    config.oam.dev/provider: terraform-azure
spec:
  provider: azure
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: azure-credentials
      key: credentials