apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: kubevela
 namespace: argocd
spec:
  destination:
    namespace: vela-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vela-core
    repoURL: https://charts.kubevela.net/core
    targetRevision: v1.5.3
    helm:
      releaseName: kubevela
      parameters:
        - name: admissionWebhooks.certManager.enabled
          value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true