apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-configurations
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: configurations
    repoURL: https://github.com/motilayo/argocd-crossplane-kubevela.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true