apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: argo
      parameters:
      - name: server.extraArgs[0]
        value: "--insecure"
      - name: dex.enabled
        value: "false"
      - name: crds.keep
        value: "false"
      - name: args.appResyncPeriod
        value: "60"
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.29.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
