apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: gateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/standard-install.yaml
    targetRevision: HEAD
  syncPolicy:
    preserveResourcesOnDeletion: false
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
