apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helm
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.9
    helm:
      releaseName: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
    syncOptions:
    - CreateNamespace=true
