---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: terraform
spec:
  package: crossplane/provider-terraform:v0.3.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1