apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: default
spec:
  provider: gcp
  region: northamerica-northeast2
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: gcp-credentials
      key: credentials